### ISSUE TITLE
Memory leakage (or just huge consumption?) 

### ISSUE THREAD

**Issue by Shagog** [cybereality/eog-modified-date-plugin#2]
What happens:
EOG with this plugin takes all memory available while browsing photos in big folder.

How to reproduce:
Create folder of about 800 .HEIC photos. Start viewing photos one by one from the first photo using EOG with this plugin and just wait :)
In my case - used 8GB of RAM + 8GB of swap at aprox. 300 hundred photos, then EOG crushed. 

Ubuntu 20.04, EOG 3.36.3

Suggestion:
Haven't looked into sources yet, but suppose its needed to unload past photos from RAM

~
BTW thank you for this plugin, missed this functionality alot! Hope you'll be able to fix this issue. Would be glad to help if anything needed.

**Comment by cybereality** [comment]
Thanks for the report. I think I might know what the problem is, I'm looking into it now.

**Comment by cybereality** [comment]
So I was able to reproduce the memory leak issue, specifically with HEIC images. However, it does not appear to be a problem with my plugin. I made a folder with about 1,000 HEIC images, and as I cycled through them, the memory usage would go up by around 100MB every second. But the same problem happened even with my plugin disabled. And I tested in another folder with just JPG/PNG/WEBP images with and without my plugin and there was no memory issue at all. So I believe the problem is with the HEIC loader library on Ubuntu.

**Comment by Shagog** [comment]
You're right: tried on folder with 3 000 jpeg images and everything went fine (memory consumption goes up and down, so garbage collector or smth works).
Also tried on heic images without plugin and eog used all memory again. 
Seems it was eog or hiec loader update recently, because several month ago everything worked.

Sorry for bothering and thanks for your plugin again :)
