### ISSUE TITLE
Cannot reverse order - preferences pane empty

### ISSUE THREAD

**Issue by wtquin** [cybereality/eog-modified-date-plugin#6]
Installed the plugin by creating ~/.local/share/eog/ and ~/.local/share/eog/plugins/ and moving all the files into that dir, which worked fine. Relaunched eog and the plugin shows up and works, but when clicking on preferences I just get an empty pane like in this screenshot:
![image](https://user-images.githubusercontent.com/55107945/161430646-8fced893-a9f0-432b-80ea-f2ec28d67098.png)

Using Fedora 35 with Gnome shell 41.4.

**Comment by cybereality** [comment]
Okay. I don't use Fedora and I haven't seen that error before. I'll have to look into it.

**Comment by wtquin** [comment]
Thank you! Let me know if you need any logs of sorts.

**Comment by RomanRiabenko** [comment]
I have just installed and tried the plugin on Fedora. Did not run into any issues.

If the issue occurs only in Fedora 35, it may not be worth the effort to fix it. Fedora 35 is [end-of-life since 13 December 2022](https://docs.fedoraproject.org/en-US/releases/eol/).

My setup:
* modified-date plugin 1.0.3 release
* Fedora 37, 64 bit
* GNOME 43.3
* GNOME Viewer (eog) 43.1

**Comment by wtquin** [comment]
Have moved on from Fedora a while ago so I cannot reproduce either. Closing the issue 👍
